insert into Employees (RestaurantId, FirstName, LastName, Position) values (21, 'Araldo', 'Bennedick', 'Quality Control Specialist');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (19, 'Clementine', 'Lettson', 'Internal Auditor');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (18, 'Filip', 'Warbys', 'Nurse');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (7, 'Izaak', 'Malone', 'Help Desk Technician');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (15, 'Fleming', 'Strahan', 'Media Manager III');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (34, 'Tore', 'Bernadot', 'Legal Assistant');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (40, 'Netta', 'Hurley', 'Financial Advisor');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (25, 'Annnora', 'Brigg', 'Financial Advisor');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (34, 'Sibyl', 'Castaignet', 'Analog Circuit Design manager');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (5, 'Lauraine', 'Hodjetts', 'Nuclear Power Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (12, 'Evelina', 'Berthel', 'Human Resources Manager');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (31, 'Joellen', 'Hylden', 'Account Coordinator');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (44, 'Clayborne', 'Bream', 'Human Resources Assistant I');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (43, 'Jamil', 'Swettenham', 'Executive Secretary');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (49, 'Brigitta', 'Leighton', 'Business Systems Development Analyst');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (2, 'Shelli', 'Regina', 'General Manager');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (39, 'Lenard', 'Boyet', 'Database Administrator III');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (14, 'Esther', 'Peniman', 'Office Assistant I');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (9, 'Lillis', 'Jobes', 'Professor');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (47, 'Webster', 'Jeste', 'Research Nurse');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (8, 'Waylin', 'Lucas', 'Web Designer III');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (27, 'Sandy', 'Shark', 'Senior Sales Associate');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (21, 'Aili', 'Clampe', 'Senior Quality Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (46, 'Base', 'Cash', 'Analyst Programmer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (36, 'Kearney', 'Asbery', 'Sales Associate');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (27, 'Byrom', 'Orfeur', 'Professor');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (8, 'Willis', 'Hattersley', 'Mechanical Systems Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (7, 'Jennilee', 'McQuillen', 'Quality Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (47, 'Jillene', 'Skuce', 'Automation Specialist I');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (39, 'Bernardine', 'Pusey', 'Tax Accountant');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (3, 'Dierdre', 'Burnsides', 'Senior Editor');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (43, 'Kesley', 'Carr', 'VP Quality Control');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (22, 'Laura', 'Skerrett', 'Help Desk Technician');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (47, 'Olly', 'Maes', 'Social Worker');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (8, 'Bondie', 'Pollins', 'Automation Specialist III');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (21, 'Derron', 'Nussii', 'Geological Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (13, 'Kevyn', 'Salmoni', 'Cost Accountant');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (24, 'Shelley', 'Sommerlin', 'Financial Analyst');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (44, 'Tonie', 'Splain', 'Financial Advisor');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (3, 'Max', 'Wem', 'Structural Analysis Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (15, 'Madeleine', 'Welband', 'Engineer III');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (28, 'Halie', 'Gamett', 'Help Desk Technician');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (33, 'Levin', 'Glassopp', 'Structural Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (23, 'Janenna', 'McCrohon', 'Chemical Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (43, 'Dorothee', 'Keogh', 'Senior Financial Analyst');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (7, 'Doris', 'Harding', 'Clinical Specialist');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (41, 'Chiquita', 'Geistmann', 'Senior Cost Accountant');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (2, 'Rodina', 'Bundock', 'Accounting Assistant II');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (18, 'Don', 'Strathern', 'Electrical Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (15, 'Lynnette', 'O''Corrigane', 'Physical Therapy Assistant');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (38, 'Courtnay', 'Cayser', 'Editor');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (5, 'Keary', 'Dagleas', 'Director of Sales');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (6, 'Paula', 'Ebbotts', 'Sales Representative');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (33, 'Seymour', 'Lead', 'Geologist II');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (1, 'Willy', 'Ilieve', 'Analog Circuit Design manager');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (18, 'Robinet', 'Blois', 'Programmer III');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (11, 'Jozef', 'Camelli', 'Media Manager III');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (46, 'Tiphanie', 'Quilty', 'Geologist II');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (38, 'Roanna', 'Linford', 'Biostatistician I');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (50, 'Carlynn', 'Boodell', 'Occupational Therapist');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (28, 'Simone', 'Fippe', 'Design Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (12, 'Kacey', 'Prater', 'Professor');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (3, 'Virgil', 'Greguol', 'Pharmacist');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (2, 'Kass', 'Elleton', 'Clinical Specialist');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (20, 'Ricardo', 'Woolaston', 'Nuclear Power Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (38, 'Marsiella', 'Camell', 'Quality Control Specialist');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (5, 'Callean', 'Stather', 'Software Test Engineer IV');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (40, 'Benedetta', 'Pitcock', 'VP Product Management');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (45, 'Leupold', 'Brownlow', 'Senior Cost Accountant');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (36, 'Valry', 'Brussels', 'Civil Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (22, 'Galvin', 'Norcliff', 'Social Worker');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (38, 'Jerrold', 'Jantot', 'Junior Executive');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (8, 'Sharron', 'Payley', 'Web Developer II');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (28, 'Candace', 'Mabee', 'Safety Technician III');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (32, 'Ebba', 'Elloy', 'Graphic Designer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (50, 'Tedra', 'Stanyan', 'Senior Sales Associate');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (48, 'Law', 'Cromar', 'Nurse');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (36, 'Trixi', 'Sharpus', 'Budget/Accounting Analyst I');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (43, 'Gabrila', 'Lewis', 'Staff Scientist');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (30, 'Torey', 'Boutellier', 'Community Outreach Specialist');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (8, 'Karlie', 'Rape', 'Account Executive');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (5, 'Gayel', 'Gheraldi', 'Human Resources Assistant III');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (35, 'Ulric', 'Brymham', 'Web Designer I');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (2, 'Alexandre', 'Shimwall', 'Automation Specialist IV');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (13, 'Adam', 'Mapplebeck', 'Product Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (48, 'Renaud', 'Stagge', 'Desktop Support Technician');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (40, 'Brook', 'Dioniso', 'Analyst Programmer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (46, 'Hedvige', 'Cowope', 'Staff Accountant II');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (33, 'Karlen', 'Belfrage', 'Operator');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (32, 'De', 'Delafont', 'Assistant Manager');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (30, 'Liuka', 'Mulderrig', 'Food Chemist');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (25, 'Jacki', 'Blackeby', 'VP Marketing');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (8, 'Cori', 'Gatley', 'Financial Analyst');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (48, 'Stephani', 'Bailie', 'Professor');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (32, 'Leonie', 'McPake', 'Assistant Professor');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (35, 'Roxanne', 'de Leon', 'Programmer III');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (9, 'Carleton', 'Laverick', 'Information Systems Manager');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (25, 'Goldia', 'Lancetter', 'Electrical Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (46, 'Zebulon', 'Dean', 'Structural Engineer');
insert into Employees (RestaurantId, FirstName, LastName, Position) values (29, 'Rollo', 'Medling', 'VP Accounting');
